# -*- coding: utf-8 -*-
"""EmployeeAttrition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSsYGMaNR-OBtXbP82TGpq5FoJUFTkaj
"""

!pip install pandas numpy matplotlib seaborn scikit-learn pyplot
!sudo apt-get install graphviz #graph is a system wide for pydot to work
#! prefeix is used for shell commands
#sudo apt is used to install the graphviz binaries

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
sns.set_style("whitegrid")

from google.colab import files
print("Please upload kaggle.json(from your kaggle account)")
files.upload()

df = pd.read_csv('Employee_attrition.csv')
df.head()

#basic health of the data/healthcheck
df.shape

display(df.dtypes)

df.isnull().sum()

df.describe()

sns.boxplot(data=df , x='DistanceFromHome')

sns.countplot(x='Attrition', data=df)

df.head()

#df.drop(['EmployeeCount','EmployeeNumber','Over18','StandardHours'],axis="columns" ,inplace=True)
# df.drop(['EmployeeCount','EmployeeNumber','Over18','StandardHours'], axis="columns", inplace=True)

categorical_col = []

for column in df.columns:
    if df[column].dtype == object and len(df[column].unique()) <= 50:
        categorical_col.append(column)

# Convert Attrition to category and remove from list
df['Attrition'] = df['Attrition'].astype('category').cat.codes

#remove attribute from categorical dataframe
if 'Attrition' in categorical_col:
    categorical_col.remove('Attrition')

#label encoding other categorical features
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
for column in categorical_col:
  df[column]=label.fit_transform(df[column])

from sklearn.model_selection import train_test_split
x=df.drop('Attrition',axis=1)
y=df.Attrition
x_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

#function to print the model scores
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
def print_score(clf ,x_train, x_test, y_train, y_test ,train=True):
  if train:
    pred = clf.predict(x_train)
    clf_report = pd.DataFrame(classification_report(y_train,pred,output_dict=True))
    print("Train Result \n=================")
    print(f"Accuracy score:{accuracy_score(y_train ,pred)*100:.2f}%")
    print("------------------------------")
    print(f"Classification Report:\n{clf_report}")
    print("------------------------------")
    print(f"Confusion Matrix:\n{confusion_matrix(y_train,pred)}\n")

  elif train == False:
    pred = clf.predict(x_test)
    clf_report = pd.DataFrame(classification_report(y_test,pred,output_dict=True))
    print("Test Result \n=================")
    print(f"Accuracy score:{accuracy_score(y_test ,pred)*100:.2f}%")
    print("------------------------------")
    print(f"Classification Report:\n{clf_report}")
    print("------------------------------")
    print(f"Confusion Matrix:\n{confusion_matrix(y_test,pred)}\n")
# the code that we have written right now is uses clf as a parameter its like a
 #place holder for an object that will be given to function that u call it because when u try to
  #print it u will get can error clf is not define , its not the valid clf object yet

from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(x_train,y_train)

print_score(tree_clf,x_train,X_test,y_train,y_test,train=True)
print_score(tree_clf,x_train,X_test,y_train,y_test,train=False)

